server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:///test
    username: root
    password: oH8r1KQTQ3rYUHZmn6xc
    driverclassname: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

mybatis:
  type-aliases-package: com.itheima.user.pojo